services:
  # Backend API Service
  - type: web
    name: sales-analytics-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/production_server_cloud.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sales-analytics-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: sales-analytics-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://your-app.onrender.com
      - key: ALLOWED_HOSTS
        value: your-app.onrender.com

  # Frontend Service
  - type: web
    name: sales-analytics-frontend
    env: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: ./frontend/public
    routes:
      - type: rewrite
        source: /api/*
        destination: https://sales-analytics-api.onrender.com/api/$1

databases:
  # PostgreSQL Database
  - name: sales-analytics-db
    databaseName: sales_analytics
    user: sales_user

  # Redis Cache
  - name: sales-analytics-redis
    type: redis
